/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package grafic;
import logic.*;
import grafic.*;

import java.util.Locale;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author kenneth
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form PrincipalView
     */
    public Principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        pin = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");
        setMaximumSize(new java.awt.Dimension(218, 146));
        setMinimumSize(new java.awt.Dimension(218, 146));

        jLabel1.setFont(new java.awt.Font("Raavi", 1, 14)); // NOI18N
        jLabel1.setText("Welcome to System");

        jLabel2.setText("Code");

        jLabel3.setText("Pin:");

        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pinKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(76, 76, 76))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(code, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(pin)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tcode;
        int tpin;
       
        
        if("".equals(code.getText())||"".equals(pin.getText())){
            JOptionPane.showMessageDialog(null,"Any field most by empty","Message",JOptionPane.WARNING_MESSAGE);    
        }
        else{
            tcode=code.getText();
            tpin=Integer.valueOf(pin.getText());
            int i=0;
            while(i<Students.liststudents.size()){
                if((Students.liststudents.get(i).getCode().equals(tcode))&&(Students.liststudents.get(i).getPin()==tpin)){
                    JOptionPane.showMessageDialog(null, "Students "+ Students.liststudents.get(i).getName()+" Login", "Message", JOptionPane.OK_CANCEL_OPTION);
                    code.setText("");
                    pin.setText("");
                    this.dispose();
                    main.scheduleW.setVisible(true);
                    break;
                }
                i++;
            }
            
            int i2=0;
            while(i2<Professor.listprofessor.size()){
            if((Professor.listprofessor.get(i2).getCode().equals(tcode))&&(Professor.listprofessor.get(i2).getPin()==tpin)){
                    JOptionPane.showMessageDialog(null, "Professor "+Professor.listprofessor.get(i2).getName() +" Login", "Message", JOptionPane.OK_CANCEL_OPTION);
                    break;
                }
                i2++;}

            int i3=0;
            while(i3<Coordinator.listcoordinator.size()){
            if((Coordinator.listcoordinator.get(i3).getCode().equals(tcode))&&(Coordinator.listcoordinator.get(i3).getPin()==tpin)){
                    code.setText("");
                    pin.setText("");
                    main.Name=Coordinator.listcoordinator.get(i3).getName(); 
                    CoordinatorW.name.setText("Welcome "+main.Name);
                    this.dispose();
                    main.coordinatorW.setVisible(true);
                    break;
                }
                i3++;}
            if(i==Students.liststudents.size()&&i2==Professor.listprofessor.size()&&i3==Coordinator.listcoordinator.size()){
            JOptionPane.showMessageDialog(null, "This information not register in the system", "Message", JOptionPane.OK_CANCEL_OPTION);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped
            char car = evt.getKeyChar();
        if(code.getText().length()>=9) {
            evt.consume();
        }
        if((car<'0' || car>'9')) {
            evt.consume();
        }
    }//GEN-LAST:event_codeKeyTyped

    private void pinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pinKeyTyped
        char car = evt.getKeyChar();
        if(pin.getText().length()>=4) {
            evt.consume();
        }
        if((car<'0' || car>'9')) {
            evt.consume();
        }
    }//GEN-LAST:event_pinKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pin;
    // End of variables declaration//GEN-END:variables
}
